# based on
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

require:
  - standard

plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

# Use the defaults from https://github.com/testdouble/standard.
inherit_gem:
  standard: config/ruby-3.2.yml

AllCops:
  TargetRubyVersion: 3.2
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  UseCache: true
  CacheRootDirectory: .
  MaxFilesInCache: 10000

# any rubocop overrides live in here

Layout/CommentIndentation:
  Exclude:
    - '**/Brewfile'

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/Dialect:
  Enabled:
    - feature
    - scenario

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  CountAsOne:
    - heredoc
    - hash
    - array
    - method_call
  Exclude:
    - spec/features/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
